### ISSUE TITLE
when you refresh the main page it duplicates the data

### ISSUE THREAD

**Issue by theTrueMikeBrown** [tehscott/710wouldstillsmash#2]
refresh and then scroll down to see it

**Comment by tehscott** [comment]
fortunately data is only added to the list again, not duplicated in the db

**Comment by theTrueMikeBrown** [comment]
True. I think a list.Clear() would fix this

**Comment by tehscott** [comment]
Fixed in 07f08faad229f84af2b18cfe2dab2629801dee10
